
USE IAPPSAM;

INSERT INTO ACCOUNT_TYPE VALUES
("SYSTEM_ADMIN"),
("SPSO_PERSONNEL"),
("NON_SPSO_PERSONNEL_HEAD"),
("NON_SPSO_PERSONNEL_EMPLOYEE");

INSERT INTO CONTACT_TYPE VALUES
("LANDLINE"),
("MOBILE"),
("FAX"),
("EMAIL"),
("WEBSITE"),
("OTHERS");

INSERT INTO DISPOSAL VALUES
("DESTROYED"),
("SOLD_AT_PRIVATE_SALE"),
("SOLD_AT_PUBLIC_AUCTION"),
("TRANSFERRED_WITHOUT_COST");

INSERT INTO MODE_OF_PROCUREMENT VALUES
("SHOPPING");

INSERT INTO UNIT VALUES 
('PCS');

INSERT INTO ITEM_STATUS VALUES
('NOT AVAILABLE'),
('AVAILABLE');

INSERT INTO ITEM_CONDITION VALUES
('UNAVAILABLE'),
('GOOD CONDITION');