INSERT INTO ACCOUNT_TYPE VALUES
("SYSTEM_ADMIN"),
("SPSO_PERSONNEL"),
("NON_SPSO_PERSONNEL_HEAD"),
("NON_SPSO_PERSONNEL_EMPLOYEE");

INSERT INTO CONTACT_TYPE VALUES
("LANDLINE"),
("MOBILE"),
("FAX"),
("EMAIL"),
("WEBSITE"),
("OTHERS");

INSERT INTO DISPOSAL VALUES
("DESTROYED"),
("SOLD_AT_PRIVATE_SALE"),
("SOLD_AT_PUBLIC_AUCTION"),
("TRANSFERRED_WITHOUT_COST");

INSERT INTO MODE_OF_PROCUREMENT VALUES
("SHOPPING");